version: '3.8'
services:
  db:
    image: postgres:15
    container_name: fleet_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres_local_senha}
      POSTGRES_DB: ${DB_NAME:-fleet_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: