/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgencyCard: typeof import('./components/AgencyCard.vue')['default']
    AgencyFormDialog: typeof import('./components/AgencyFormDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CarCard: typeof import('./components/CarCard.vue')['default']
    CarForm: typeof import('./components/CarForm.vue')['default']
    CarFormDialog: typeof import('./components/CarFormDialog.vue')['default']
    FinalizeRentalDialog: typeof import('./components/FinalizeRentalDialog.vue')['default']
    GlobalAlerts: typeof import('./components/core/GlobalAlerts.vue')['default']
    GlobalSnackbar: typeof import('./components/GlobalSnackbar.vue')['default']
    RentalBookingDialog: typeof import('./components/RentalBookingDialog.vue')['default']
    RentalDetailsExpanded: typeof import('./components/RentalDetailsExpanded.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserFormDialog: typeof import('./components/UserFormDialog.vue')['default']
  }
}
