/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgencyCard: typeof import('./components/AgencyCard.vue')['default']
    AgencyFormDialog: typeof import('./components/AgencyFormDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CarCard: typeof import('./components/CarCard.vue')['default']
    CarForm: typeof import('./components/CarForm.vue')['default']
    CarFormDialog: typeof import('./components/CarFormDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
